	<!-- bof header -->
	<div id="pageTitle">
		<div class="header">WEBSITE TERMS AND CONDITIONS</div>
		<div class="subheader">Update Date: September 27, 2005</div>
	</div>
	<!-- eof header -->

	<!-- bof body -->
	<div class="body_container">
		<p class="terms">The following Website Terms and Conditions Agreement (the &ldquo;Agreement&rdquo;) governs your use of the Website[s] accessible at universal resource locators laxstats.net and kaaterskil.com (collectively the &ldquo;Service&rdquo;) which are operated by Kaaterskil Management, LLC (&ldquo;Kaaterskil Management&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;). Your use of the Service constitutes your acceptance of the Agreement. Your acceptance of the Agreement provides you with a limited and temporary license and permission to use the software and other resources of the Service, which license and permission are freely revocable at any time, with or without cause, and with or without notice, by us, as described more fully below. Please print a copy of this document for your records. To retain an electronic copy of this Agreement, you may save it into any word processing program.</p> 
		
		<p class="termsHeader">1. Copyright Rights</p> 
		<p class="terms">All copyright rights in the text, blog, blog postings, images, photographs, graphics, user interface, &ldquo;laxstats Chalkboard&rdquo; application or its saved instances (collectively the &ldquo;Application&rdquo;), and other content provided on the Service, and the selection, coordination, and arrangement of such content, are owned by Kaaterskil Management, as applicable among us, or our third-party licensors, to the full extent provided under the United States Copyright laws and all international copyright laws. Under applicable copyright laws, you are prohibited from copying, reproducing, modifying, distributing, displaying, performing or transmitting any of the contents of the Service for any purposes. You may not modify, adapt, translate, rent, lease, loan, resell, distribute, network or create derivative works of the Application. You may not reverse engineer, decompile or disassemble the Application. Nothing stated or implied on the Service confers on you any license or right under any copyright of Kaaterskil Management, or any third party.</p> 
		<p class="terms">The Service and the information contained in reference herein are for informational purposes only. Any reproduction, copying, or redistribution for commercial purposes of any materials, applications or design elements of the Service is strictly prohibited, without the prior written consent of Kaaterskil Management. Systematic retrieval of data or other content from this Service to create or compile, directly or indirectly, a collection, compilation, database or directory without written permission from Kaaterskil Management is prohibited.</p> 
		
		<p class="termsHeader">2. Trade and Service Mark Rights </p>
		<p class="terms">All rights in the product names, company names, trade names, logos, product packaging and designs of all Kaaterskil Management or third-party products or services, whether or not appearing in large print or with the trademark symbol, belong exclusively to Kaaterskil Management, as applicable, or their respective owners, and are protected from reproduction, imitation, dilution or confusing or misleading uses under national and international trademark and copyright laws, as applicable. The use or misuse of these trademarks or any materials, except as permitted herein, is expressly prohibited and nothing stated or implied on this Service confers on you any license or right under any patent, copyright or trademark of Kaaterskil Management or any third party.</p> 
		
		<p class="termsHeader">3. Modification of This Agreement</p>
		<p class="terms">Kaaterskil Management reserves the right to amend this Agreement at any time. You are bound by any such revisions and should therefore periodically visit this page to review the then-current Terms and Conditions to which you are bound. Your use of the Service after the posting of modifications to this Agreement will constitute your acceptance of this Agreement, as modified. If, at any time, you do not wish to accept this Agreement, you may not use the Service. </p>
		
		<p class="termsHeader">4. Links </p>
		<p class="terms">This Service may contain links to other services (&ldquo;Linked Services&rdquo;). The Linked Services are not under the control of Kaaterskil Management, and Kaaterskil Management is not responsible for the contents of the Linked Services, including, without limitation, links contained on Linked Services, or any changes or updates to Linked Services. Kaaterskil Management provides any Linked Services to you only as a convenience, and the inclusion of any such Linked Services is not an endorsement by Kaaterskil Management in favor of any company offering Internet services, products or services on the Linked Services. </p>
		<p class="terms">Other sites may link without prior permission to the home page of the Service only through a plain-text link. Permission must otherwise be granted by us for any other type of link to the Service. To seek our permission, you may write to Kaaterskil Management, 45 Avon Road, Wellesley, MA  02482. Additional Agreement by Linked Services: any third party Web site that links to the Service: (a) shall not create a frame, browser or border environment around any of the content of the Service; (b) may link to, but not replicate, Service content; (c) shall not imply that Kaaterskil Management is endorsing or sponsoring it or its products or services; (d) shall not present false information about Kaaterskil Management or its products or services; (e) shall not use Kaaterskil Management trademarks without the prior written permission from Kaaterskil Management; and (f) shall not contain content that could be construed as distasteful, offensive or controversial.</p> 
		<p class="terms">Notwithstanding anything to the contrary contained in this Agreement, we reserve the right to deny or rescind permission to link to the Service from any Website, and to require termination of any link to the Service, for any reason in our sole and absolute discretion.</p> 
		
		<p class="termsHeader">5. Obligations</p> 
		<p class="terms">You are required to comply with all applicable law in connection with your use of the Service, and such further limitations as may be set forth in any written or on-screen notice from Kaaterskil Management. As a condition of your use of the Service, you represent and warrant that you will not use the Service for any purpose that is unlawful or prohibited by this Agreement. </p>
		
		<p class="termsHeader">6. Prohibited Uses Generally</p> 
		<p class="terms">Without limiting the foregoing, you agree not to transmit, distribute, post, communicate or store information or other material on, to or through the Service that:</p> 
		<div class="indent">
			<p class="terms">(a) is copyrighted, unless you are the copyright owner or valid licensee to such materials and you have the right to grant Kaaterskil Management the rights and licenses set forth in Section 8 of this Agreement;</p>
			<p class="terms">(b) reveals trade secrets, unless you own them, or you are the valid licensee to such materials and you have the right to grant Kaaterskil Management the rights and licenses set forth in Section 8 of this Agreement;</p>
			<p class="terms">(c) infringes on any other intellectual property rights of others or on the privacy or publicity rights of others;</p>
			<p class="terms">(d) is obscene, defamatory, threatening, harassing, abusive, hateful, slanderous or embarrassing to any other person or entity or in violation of applicable law as determined by Kaaterskil Management in our sole discretion;</p>
			<p class="terms">(e) is sexually-explicit;</p>
			<p class="terms">(f) constitutes advertisements or solicitations of business, surveys, contests, chain letters or pyramid schemes; or</p>
			<p class="terms">(g) contains viruses, Trojan horses, worms, time bombs, or other computer programming routines or engines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or information.</p>
		</div>
		
		<p class="terms">You further agree not to:</p>
		<div class="indent">
			<p class="terms">(a) use any incomplete, false or inaccurate biographical information or other information for purposes of registering as a user of the Service, or for purposes of registering for any promotions offered through the Service;</p>
			<p class="terms">(b) delete or revise any material or other information of any other user of the Service;</p>
			<p class="terms">(c) harvest, collect, or send information about others, including e-mail addresses, without their consent;</p>
			<p class="terms">(d) take any action that imposes an unreasonable or disproportionately large load on the Service’s infrastructure;</p>
			<p class="terms">(e) use any device, software or routine to interfere or attempt to interfere with the proper working of the Service or any activity being conducted on this site;</p>
			<p class="terms">(f) use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatar’s or intelligent agents) to navigate or search the Service to harvest or otherwise collect information from the Service to be used for any commercial purpose;</p>
			<p class="terms">(g) allow any other person or entity to use your username or password for posting or viewing comments or sending or receiving materials; or</p>
			<p class="terms">(h) attempt to decipher, decompile, disassemble or reverse engineer any of the software comprising or in any way making up a part of the Service.</p>
		</div>
		
		<p class="terms">You further agree not to violate or attempt to violate the security of the Service, including, without limitation:</p>
		<div class="indent">
			<p class="terms">(a) accessing data not intended for you or logging into a server or account that you are not authorized to access;</p>
			<p class="terms">(b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization;</p>
			<p class="terms">(c) attempting to interfere with service to any user, host or network, including, without limitation, by way of submitting a virus to, or overloading, &ldquo;flooding&rdquo;, &ldquo;spamming&rdquo;, &ldquo;mailbombing&rdquo; or &ldquo;crashing&rdquo;, the Service;</p>
			<p class="terms">(d) sending unsolicited e-mail, including promotions and/or advertising of products or services; or</p>
			<p class="terms">(e) forging any TCP/IP packet header or any part of the header information in any e-mail or posting. Violations of system or network security may result in civil or criminal liability.</p>
		</div>
		<p class="terms">Kaaterskil Management may investigate occurrences that may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations.</p>	
		<p class="terms">Kaaterskil Management reserves the right (but does not have the obligation) to review postings on its Service, to remove any postings, and to terminate your ability to post to the Service at any time without notice, in its sole discretion. Kaaterskil Management also reserves the right to disclose any information necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part. </p>
		
		<p class="termsHeader">7. Conduct </p>
		<p class="terms">You are responsible for, and assume all liability associated with, any material you make available or transmit through the Service, whether through chat rooms, messages boards or other forums, including liability for claims of infringement, libel and slander. You may not post, transmit through or otherwise make available on or through the Service (i) any material that violates or infringes in any way upon the rights of others, that is unlawful, defamatory, obscene, abusive, profane, vulgar, sexually explicit, racist, threatening, hateful or otherwise objectionable or that encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law, (ii) without the express written consent of the owner thereof, any copyrighted material, or (iii) without the express prior written consent of Kaaterskil Management any advertising or any solicitation with respect to products or services (unless posted in an area specifically designated for that purpose). Although Kaaterskil Management does not and cannot review every message posted on or transmitted through the Service, Kaaterskil Management shall be under no obligation to permit any material posted or transmitted to remain on the Service, and may remove from, or refuse to display on the Service any material that Kaaterskil Management, in the exercise of our sole discretion, believe violates this Agreement.</p>
		
		<p class="termsHeader">8. License Granted </p>
		<p class="terms">We do not claim ownership of any information or material you transmit, distribute, post, communicate or store on, to or through the Service (expressly excluding your user data which is collected in accordance with the Service Privacy Policy) (&ldquo;Your Content&rdquo;). However, by submitting or posting Your Content, to or through the Service, you grant Kaaterskil Management a world-wide, royalty free, perpetual, irrevocable and non-exclusive right (including any moral rights) and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display Your Content anywhere, for any purpose, and in any form, media or technology now known or later developed. No compensation will be paid with respect to the use of Your Content. Kaaterskil Management is free to use any ideas, concepts, know-how, or techniques contained in Your Content for any purpose whatsoever including, but not limited to, developing, manufacturing and marketing products using Your Content. Kaaterskil Management is under no obligation to maintain any of Your Content and may remove any of Your Content at any time in its sole discretion.</p> 
		<p class="terms">By posting or submitting Your Content to this Service, you also represent and warrant that you own or otherwise control all of the rights to Your Content, and that use of Your Content by Kaaterskil Management will not infringe or violate the rights of any third party or violation applicable law. </p>
		
		<p class="termsHeader">9. Notice of Copyright Infringement </p>
		<p class="terms">If you believe that your work has been copied and is accessible on this Service in a way that constitutes copyright infringement, please provide Kaaterskil Management with the following information: </p>
		<div class="indent">
			<p class="terms">(a) identification of the copyrighted work claimed to have been infringed; </p>
			<p class="terms">(b) identification of the allegedly infringing material on the Service that is requested to be removed; </p>
			<p class="terms">(c) your name, address and daytime telephone number, and an e-mail address if available, so that we may contact you if necessary; </p>
			<p class="terms">(d) a statement that you have a good faith belief that the use of the copyrighted work is not authorized by the copyright owner, its agent, or the law; </p>
			<p class="terms">(e) a statement that the information in the notification is accurate, and under penalty of perjury, that the signatory is authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed; and </p>
			<p class="terms">(f) an electronic or physical signature of the copyright owner or someone authorized on the owner’s behalf to assert infringement of copyright and to submit the statement. </p>
		</div>
		<p class="terms">Kaaterskil Management may be contacted at 45 Avon Road, Wellesley, Massachusetts  02482.</p>
		<p class="terms">Kaaterskil Management reserves the right to remove any posted submission which infringes the copyright of any person under the laws of the United States upon receipt of such a statement (or, more specifically, any statement in conformance with 17 U.S.C. § 512(c)(3)). United States law provides significant penalties for submitting such a statement falsely. </p>
		
		<p class="termsHeader">10. Registration, Username, Password, Security. </p>
		<p class="terms">(a) <font style="text-decoration:underline; ">Registration</font>. Registration may be required for the use of certain portions of the Service. Your registration shall not impose any duty on us to provide any particular service to you. If the terms of any Kaaterskil Management registration agreement conflict with the terms of this Agreement, the registration agreement shall control.</p> 
		<p class="terms">(b) <font style="text-decoration:underline; ">Your User Identity</font>. Your username and password will be your identity for purposes of interacting with Service and other users through the Service. </p>
		<p class="terms">(c) <font style="text-decoration:underline; ">User Name, Passwords, and Password Access</font>. You shall keep confidential, shall not disseminate, and shall use solely in accordance with this Agreement, your username, and password for the Service. You shall immediately notify Kaaterskil Management if you learn of or suspect: (i) any loss or theft of your username or password, or (ii) any unauthorized use of your username or password or of the Service. In the event of such loss, theft, or unauthorized use, Kaaterskil Management may impose on you, at Kaaterskil Management’s sole discretion, additional security obligations. </p>
		<p class="terms">(d) <font style="text-decoration:underline; ">Security Breaches and Revision</font>. If any unauthorized person obtains access to the Service as a result of any act or omission by you, you shall use your best efforts to ascertain the source and manner of acquisition and shall fully and promptly brief Kaaterskil Management. You shall otherwise cooperate and assist in any investigation relating to any such unauthorized access. </p>
		
		<p class="termsHeader">11. Privacy Policy </p>
		<p class="terms">We are committed to protecting your privacy and security and have explained in detail the steps we take to do so in the Service Privacy Policy, a copy of which you should review by clicking <a href="../../../content/help/terms/privacy.htm">here</a>. You in turn agree and consent to the terms of the Service Privacy Policy by your use of the Service. </p>
		
		<p class="termsHeader">12. Access to the Service </p>
		<p class="terms">In order to access the Service, you must have access to the World Wide Web, either directly or through devices that access web-based content, and pay any service fees associated with such access. In addition, you must use all equipment necessary to make such connection to the World Wide Web, including a computer and modem or other access device.</p> 
		
		<p class="termsHeader">13. Disclaimer of Warranties </p>
		<p class="terms">THE SERVICE IS PROVIDED &ldquo;AS IS.&rdquo; KAATERSKIL MANAGEMENT MAKES NO REPRESENTATION OR WARRANTY OF ANY KIND WHATSOEVER TO YOU OR ANY OTHER PERSON RELATING IN ANY WAY TO THE SERVICE, INCLUDING ANY PART THEREOF, OR ANY WEB SITE OR OTHER CONTENT OR SERVICE THAT MAY BE ACCESSIBLE DIRECTLY OR INDIRECTLY THROUGH THE SERVICE. KAATERSKIL MANAGEMENT DISCLAIMS TO THE MAXIMUM EXTENT PERMITTED BY LAW, ANY AND ALL SUCH REPRESENTATIONS AND WARRANTIES. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, KAATERSKIL MANAGEMENT DISCLAIMS TO THE MAXIMUM EXTENT PERMITTED BY LAW ANY AND ALL (i) WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, (ii) WARRANTIES AGAINST INFRINGEMENT OF ANY THIRD PARTY INTELLECTUAL PROPERTY OR PROPRIETARY RIGHTS, (iii) WARRANTIES RELATING TO DELAYS, INTERRUPTIONS, ERRORS, OR OMISSIONS IN THE SERVICE, OR ANY PART THEREOF, (iv) WARRANTIES RELATING TO THE TRANSMISSION OR DELIVERY OF THE SERVICE, (v) WARRANTIES RELATING TO THE ACCURACY OR CORRECTNESS OF DATA, AND (vi) WARRANTIES OTHERWISE RELATING TO PERFORMANCE, NONPERFORMANCE, OR OTHER ACTS OR OMISSIONS BY KAATERSKIL MANAGEMENT OR ANY THIRD PARTY. FURTHER, AND WITHOUT LIMITING THE GENERALITY OF ANY OF THE FOREGOING, THERE IS NO WARRANTY THAT THE SERVICE WILL MEET YOUR NEEDS OR REQUIREMENTS OR THE NEEDS OR REQUIREMENTS OF ANY OTHER PERSON.</p> 
		<p class="terms">KAATERSKIL MANAGEMENT MAKES NO WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED, THAT THE INFORMATION PROVIDED THROUGH THE SERVICE WILL BE FREE FROM ERROR, OMISSION, INTERRUPTION, DEFECT, OR DELAY IN OPERATION. ANY INFORMATION ON THIS SERVICE IS SUBJECT TO CHANGE WITHOUT NOTICE, AND WE DISCLAIM ALL RESPONSIBILITY FOR THESE CHANGES, INCLUDING, BUT NOT LIMITED TO, CHANGES TO PRICES, DISCOUNTS, AND HOURS OF OPERATION.</p> 
		
		<p class="termsHeader">14. Limitation of Liability </p>
		<p class="terms">IN NO EVENT WILL KAATERSKIL MANAGEMENT OR THEIR OWNERS, AFFILIATES, OR ANY PARTY INVOLVED IN CREATING, PRODUCING OR DELIVERING THIS SERVICE, OR ON ANY WEBSITE LINKED TO THIS SERVICE, BE LIABLE IN ANY MANNER WHATSOEVER FOR ANY DIRECT, INCIDENTAL, CONSEQUENTIAL, INDIRECT, SPECIAL OR PUNITIVE DAMAGES ARISING OUT OF YOUR ACCESS, USE OR INABILITY TO USE THIS SERVICE OR ANY SITE LINKED TO THIS SERVICE, OR IN CONNECTION WITH ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS OR LINE OR SYSTEM FAILURE. IN NO EVENT SHALL KAATERSKIL MANAGEMENT OR THEIR AFFILIATES OR ANY THIRD PARTY BE LIABLE TO YOU OR ANY OTHER PERSON FOR CONSEQUENTIAL, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR INDIRECT DAMAGES ARISING UNDER OR IN ANY WAY RELATED TO THE SERVICE, INCLUDING ANY PART THEREOF, OR ANY OTHER CONTENT, (INCLUDING LOST PROFITS, LOSS OF BUSINESS OR DATA, BUSINESS INTERRUPTION, TRADING LOSSES, AND DAMAGES THAT RESULT FROM INACCURACY OF THE INFORMATION OR INCONVENIENCE, DELAY, OR LOSS OF THE USE OF THE SERVICE) EVEN IF KAATERSKIL MANAGEMENT OR ANY THIRD PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES.</p> 
		<p class="terms">KAATERSKIL MANAGEMENT RESERVES THE RIGHT TO ALTER THE CONTENT OF THIS SERVICE IN ANY WAY, AT ANY TIME, FOR ANY REASON, WITHOUT PRIOR NOTIFICATION, AND WILL NOT BE LIABLE IN ANY WAY FOR POSSIBLE CONSEQUENCES OF SUCH CHANGES. THESE LIMITATIONS APPLY WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF KAATERSKIL MANAGEMENT HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, KAATERSKIL MANAGEMENT’ LIABILITY IN SUCH JURISDICTIONS SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p> 
		<p class="terms">IN NO EVENT SHALL KAATERSKIL MANAGEMENT’S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, OR CAUSES OF ACTION ARISING UNDER THIS AGREEMENT EXCEED ONE HUNDRED DOLLARS ($100.00). </p>
		
		<p class="termsHeader">15. Indemnification </p>
		<p class="terms">Upon a request by Kaaterskil Management, you agree to indemnify and hold harmless Kaaterskil Management and their respective owners, subsidiaries, affiliates, directors, officers, agents, licensors, co-branders or other partners and employees from and against all liabilities, claims and expenses, including reasonable attorneys’ fees, made by any third party due to or arising out of content you submit, post to or transmit through this Service, your use of the Service, your violation of this Agreement or your violation of any rights of another. </p>
		
		<p class="termsHeader">16. Choice of Law and Forum </p>
		<p class="terms">This Agreement shall be governed by and construed in accordance with the laws of the State of New York, excluding its conflict of law rules. You expressly consent and agree to submit to the exclusive jurisdiction and venue of the United States District Court for the Southern District of New York or, for matters not susceptible of adjudication in the federal courts, the courts of the State of New York located in New York County, in all disputes arising out of or relating to the use of this Service. </p>
		
		<p class="termsHeader">17. United States Jurisdiction </p>
		<p class="terms">The Service is operated in the United States of America. We do not represent that content or materials presented on the Service are appropriate or available for use in other locations. If you access the Service from a jurisdiction other than the United States, you agree that you do so on your own initiative, and are responsible for compliance with local laws, if and to the extent local laws are applicable to your use of the Service. </p>
		
		<p class="termsHeader">18. Severability and Integration </p>
		<p class="terms">Unless otherwise specified herein, this Agreement constitutes the entire agreement between you and Kaaterskil Management and governs your use of this Service, superseding any prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and Kaaterskil Management. If any portion of this Agreement is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intention of the parties, and the remaining portions shall remain in full force and effect. This agreement may be modified only by our posting on the Service changes to this Agreement, or by a subsequent writing signed by Kaaterskil Management.</p>
		
		<p class="termsHeader">19. No Waiver </p>
		<p class="terms">The failure of Kaaterskil Management to enforce any provisions of this Agreement or respond to a breach by you or other parties shall not in any way waive its right to enforce subsequently any terms or conditions of this Agreement or to act with respect to similar breaches. </p>
		
		<p class="termsHeader">20. No Professional Advice </p>
		<p class="terms">Any information supplied by any employee or agent of Kaaterskil Management, whether by telephone, e-mail, letter, facsimile or other form of communication, is intended solely as general guidance on the use of the Service, and does not constitute legal, tax, accounting or other professional advice. Individual situations and state laws vary and users are encouraged to obtain appropriate advice from qualified professionals in the applicable jurisdictions. Kaaterskil Management makes no representations or warranties concerning any course of action taken by any person following or otherwise using the information offered or provided within or through the Service, and Kaaterskil Management will not be liable for any direct, indirect, consequential, special, exemplary or other damages that may result, including but not limited to economic loss, injury, illness or death. </p>
		
		<p class="termsHeader">21. Miscellaneous </p>
		<p class="terms">You agree that no joint venture, partnership, employment, or agency relationship exists between you and Kaaterskil Management as a result of this Agreement or your use of this Service. Nothing contained in this Agreement is in derogation of Kaaterskil Management’ right to comply with governmental, court and law enforcement requests or requirements relating to your use of this Service or information provided to or gathered by Kaaterskil Management with respect to such use. A printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p> 
		
		<p class="termsHeader">22. Termination </p>
		<p class="terms">Kaaterskil Management reserves the right, in its sole discretion, to terminate this Agreement and your access to all or part of this Service, with or without notice and with or without cause. Termination of your access to this Service means the revocation of the limited and temporary license and permission to use the software and other resources of the Service granted to you under this Agreement by Kaaterskil Management. The provisions of this Agreement will survive the termination of your access to the Service and of this Agreement. </p>
		
		<p class="termsHeader">23. Notices </p>
		<p class="terms">Kaaterskil Management may give notices to users of the Service, at Kaaterskil Management’s option, by posting a message on the Service, by electronic or conventional mail or by any other means by which users obtain actual knowledge thereof. Notices by users to Kaaterskil Management must be given by electronic or conventional mail. Notices to Kaaterskil Management by electronic mail must be sent to <a href="mailto:questions@kaaterskil.com">questions@kaaterskil.com</a>. Notices to Kaaterskil Management by conventional mail must be sent to: Kaaterskil Management, LLC, 45 Avon Road, Wellesley, MA  02482. Notices by a user to Kaaterskil Management will not change the terms of this Agreement unless the change is expressly accepted in writing by an authorized officer of Kaaterskil Management.</p> 
		<p class="termsHeader">24. Violations. </p>
		<p class="terms">Please report any violations of this Agreement to Kaaterskil Management at 339-788-1974. </p>
	</div>
	<!-- eof body -->
